export const FETCH_AUTH_START = "FETCH_USERDATA_START"
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS"
export const FETCH_AUTH_FAILURE = "FETCH_AUTH_FAILURE"
export const CLEAR_ERROR = "CLEAR_ERROR"
